const majorArcana=[
  ["愚者","The Fool","✧","新的开始、信任直觉、轻装上路","冲动、逃避现实、准备不足"],
  ["魔术师","The Magician","∞","意志、资源、主动创造","操控、能量分散、尚未落实"],
  ["女祭司","The High Priestess","☾","直觉、静观、隐而未显","忽略直觉、信息遮蔽、内在噪音"],
  ["皇后","The Empress","♀","滋养、丰盛、关系生长","过度付出、依赖、创造受阻"],
  ["皇帝","The Emperor","♙","秩序、边界、稳定掌控","僵化、控制、权威冲突"],
  ["教皇","The Hierophant","⌘","传统、指引、共同价值","打破惯例、教条、价值分歧"],
  ["恋人","The Lovers","♡","联结、选择、价值一致","失衡、摇摆、关系错位"],
  ["战车","The Chariot","♜","决心、推进、驾驭冲突","失控、方向不一、急于求成"],
  ["力量","Strength","♌","温柔的勇气、自持、韧性","自我怀疑、压抑、力量耗损"],
  ["隐者","The Hermit","♢","独处、求索、内在答案","孤立、回避、过度内省"],
  ["命运之轮","Wheel of Fortune","⊕","周期转折、机遇、变化","阻滞、抗拒变化、旧循环"],
  ["正义","Justice","⚖","因果、公平、清醒决断","偏见、失衡、逃避责任"],
  ["倒吊人","The Hanged Man","♆","暂停、换位、主动放下","徒劳等待、拖延、抗拒牺牲"],
  ["死神","Death","☠","结束、蜕变、腾出空间","留恋旧局、害怕结束、停滞"],
  ["节制","Temperance","△","调和、耐心、循序渐进","过量、失调、节奏混乱"],
  ["恶魔","The Devil","♑","执着、欲望、看见束缚","松绑、觉察依赖、重获选择"],
  ["高塔","The Tower","ϟ","真相冲击、结构瓦解、觉醒","避免灾变、延迟改变、内在动荡"],
  ["星星","The Star","✦","希望、疗愈、真实愿景","失望、信念减弱、需要充电"],
  ["月亮","The Moon","☽","潜意识、暧昧、穿越不安","迷雾渐散、压抑恐惧、自我欺骗"],
  ["太阳","The Sun","☀","清晰、活力、坦诚喜悦","短暂阴霾、过度乐观、喜悦延迟"],
  ["审判","Judgement","♬","召唤、复盘、重获新生","自我苛责、拒绝回应、犹疑"],
  ["世界","The World","◎","完成、整合、进入新阶段","尚未收尾、缺少闭环、临门一步"]
].map((c,i)=>({id:i,...Object.fromEntries([["name",c[0]],["en",c[1]],["symbol",c[2]],["upright",c[3]],["reversed",c[4]]])}));

const minorSuits=[
  {name:"权杖",en:"Wands",symbol:"♨",upright:"行动、热情与创造力正在推动事情发展",reversed:"行动受阻、精力分散或热情消耗过快"},
  {name:"圣杯",en:"Cups",symbol:"♧",upright:"情感、关系与直觉正在成为重要线索",reversed:"情绪淤积、关系失衡或感受尚未被诚实面对"},
  {name:"宝剑",en:"Swords",symbol:"†",upright:"思考、沟通与清晰判断带来突破",reversed:"思绪紧绷、沟通受阻或陷入过度分析"},
  {name:"星币",en:"Pentacles",symbol:"✥",upright:"现实资源、稳定积累与长期价值正在成形",reversed:"现实基础不稳、资源使用失衡或进展迟缓"}
];
const minorRanks=[
  {name:"首牌",en:"Ace",theme:"一个崭新的起点与纯粹潜能"},
  {name:"二",en:"Two",theme:"权衡两股力量并寻找平衡"},
  {name:"三",en:"Three",theme:"合作、扩展与初步成果"},
  {name:"四",en:"Four",theme:"建立结构、稳定与边界"},
  {name:"五",en:"Five",theme:"冲突、考验与重新调整"},
  {name:"六",en:"Six",theme:"流动、修复与阶段性进展"},
  {name:"七",en:"Seven",theme:"评估局面并坚持自己的选择"},
  {name:"八",en:"Eight",theme:"加速、练习与持续推进"},
  {name:"九",en:"Nine",theme:"接近完成，同时守护已有成果"},
  {name:"十",en:"Ten",theme:"周期抵达高点并准备转换"},
  {name:"侍从",en:"Page",theme:"好奇、学习与新消息"},
  {name:"骑士",en:"Knight",theme:"带着目标投入行动"},
  {name:"王后",en:"Queen",theme:"成熟地承载并滋养这股能量"},
  {name:"国王",en:"King",theme:"掌控、责任与稳定表达"}
];
const minorArcana=minorSuits.flatMap(suit=>minorRanks.map(rank=>({
  name:`${suit.name}${rank.name}`,
  en:`${rank.en} of ${suit.en}`,
  symbol:suit.symbol,
  upright:`${rank.theme}；${suit.upright}`,
  reversed:`${rank.theme}尚未顺畅展开；${suit.reversed}`
})));
const cards=[...majorArcana,...minorArcana].map((card,id)=>({...card,id}));
const majorImageNames=["Fool","Magician","High Priestess","Empress","Emperor","Hierophant","Lovers","Chariot","Strength","Hermit","Wheel of Fortune","Justice","Hanged Man","Death","Temperance","Devil","Tower","Star","Moon","Sun","Judgement","World"];
const minorImageSuits=["Wands","Cups","Swords","Pents"];
function cardImageUrl(card){let filename;if(card.id<22){filename=`RWS Tarot ${String(card.id).padStart(2,'0')} ${majorImageNames[card.id]}.jpg`}else{const minorIndex=card.id-22,suit=minorImageSuits[Math.floor(minorIndex/14)],rank=minorIndex%14+1;filename=`${suit}${String(rank).padStart(2,'0')}.jpg`}return `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(filename)}?width=480`}

const spreads={
  love:{name:"关系镜像",description:"看见双方感受与关系方向",positions:["你的状态","对方的状态","关系的核心","发展趋势"]},
  career:{name:"事业罗盘",description:"辨认机会、阻力与行动方向",positions:["当前处境","你的优势","隐藏阻力","行动建议"]},
  finance:{name:"资源方阵",description:"梳理基础、流动、风险与稳健行动",positions:["当前基础","资源流动","潜在风险","稳健行动"]},
  study:{name:"学习阶梯",description:"看见基础、优势、阻碍与突破方法",positions:["当前基础","学习优势","关键阻碍","突破方法"]},
  choice:{name:"双径抉择",description:"比较两条路径与真正需求",positions:["选择 A 的能量","选择 A 的趋势","选择 B 的能量","选择 B 的趋势","内心真正需要"]},
  self:{name:"内在三镜",description:"觉察现状、盲点与成长方向",positions:["此刻的你","未被看见的部分","可以尝试的方向"]},
  timing:{name:"时间之流",description:"观察近期起点、发展过程与可能趋势",positions:["近期起点","发展过程","可能趋势"]},
  general:{name:"日常指引",description:"适合普通问题、其他主题与快速指引",positions:["当前局面","关键影响","下一步建议"]}
};
const keywords={
  finance:/财运|财务|收入|工资|薪资|存款|预算|金钱|资金|债务|消费|房租|资源/,
  study:/学习|学业|考试|考研|高考|留学|论文|作业|课程|成绩|复习|证书|面试准备/,
  love:/感情|恋爱|关系|对方|复合|婚姻|喜欢|爱情|伴侣|暧昧/,
  career:/工作|事业|职业|公司|项目|升职|创业|求职|简历|作品集|同事|老板|岗位/,
  choice:/选择|还是|要不要|两难|决定|留下|离开|选哪|二选一/,
  timing:/什么时候|何时|多久|未来|接下来|近期|本月|下月|今年|明年|三个月|半年|趋势/,
  self:/自己|成长|内心|焦虑|迷茫|状态|疗愈|改变|意义|情绪|自信/
};
const agentProviders={
  codex:{label:"Codex",detail:"默认深度解析",connected:true,vision:true}
};
const state={question:"",category:"general",agent:"codex",spread:spreads.general,selected:[],sequences:[],drawn:[],drawTime:null,readingId:null,imageData:null,imageMime:null,imageName:null,visionCards:[],codexAnalysis:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const screens={question:$("#questionScreen"),image:$("#imageScreen"),shuffle:$("#shuffleScreen"),select:$("#selectScreen"),result:$("#resultScreen")};
function showScreen(name){Object.entries(screens).forEach(([k,v])=>v.classList.toggle("is-visible",k===name));const order=["question","shuffle","select","result"],n=name==='image'?3:order.indexOf(name);$$('.step').forEach((el,i)=>{el.classList.toggle('is-active',i===n);el.classList.toggle('is-done',i<n)});window.scrollTo({top:0,behavior:"smooth"})}
function inferCategory(q){for(const [key,re] of Object.entries(keywords))if(re.test(q))return key;return "general"}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2200)}
function reset(){state.question="";state.category="general";state.agent="codex";state.selected=[];state.sequences=[];state.drawn=[];state.readingId=null;state.imageData=null;state.imageMime=null;state.imageName=null;state.visionCards=[];state.codexAnalysis=null;$("#questionForm").reset();$("#charCount").textContent="0 / 120";$("#questionHint").textContent="可输入文字，也支持 Ctrl／⌘ + V 粘贴图片";$("#imagePreview").hidden=true;$("#imagePreviewImg").removeAttribute('src');$("#submitModeLabel").textContent="进入仪式";$("#visionResult").hidden=true;$("#sharePanel").hidden=true;$("#resultTitle").textContent="牌面已经回应";$$('.category-row button').forEach(b=>b.classList.remove('selected'));if(new URLSearchParams(location.search).has("share"))history.replaceState(null,"",location.pathname);showScreen("question");closeSidebar()}

const defaultQuestionHint="可输入文字，也支持 Ctrl／⌘ + V 粘贴图片";
function attachSpreadImage(file,source="上传"){if(!file)return false;if(!/^image\/(jpeg|png|webp)$/.test(file.type)){toast("请选择 JPG、PNG 或 WebP 图片");return false}if(file.size>10*1024*1024){toast("图片不能超过 10MB");return false}const reader=new FileReader();reader.onload=()=>{state.imageData=reader.result;state.imageMime=file.type;state.imageName=file.name||`${source}的牌阵图片`;$("#imagePreviewImg").src=state.imageData;$("#imageFileName").textContent=state.imageName;$("#imagePreview").hidden=false;$("#submitModeLabel").textContent="进入仪式";$("#questionHint").textContent="图片已附加，可继续补充问题；进入后将直接生成解析";toast(`${source}图片已附加`)};reader.readAsDataURL(file);return true}
$("#questionInput").addEventListener("input",e=>$("#charCount").textContent=`${e.target.value.length} / 120`);
$("#questionInput").addEventListener("paste",e=>{const imageItem=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith("image/"));if(!imageItem)return;const file=imageItem.getAsFile();if(!file)return;e.preventDefault();attachSpreadImage(new File([file],`粘贴的牌阵-${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}).replace(':','')}.${file.type.split('/')[1]||'png'}`,{type:file.type}),"粘贴")});
$("#spreadImageInput").addEventListener("change",e=>{const file=e.target.files?.[0];if(!attachSpreadImage(file,"上传"))e.target.value=""});
$("#removeSpreadImage").addEventListener("click",()=>{state.imageData=null;state.imageMime=null;state.imageName=null;$("#spreadImageInput").value="";$("#imagePreview").hidden=true;$("#imagePreviewImg").removeAttribute('src');$("#submitModeLabel").textContent="进入仪式";$("#questionHint").textContent=defaultQuestionHint;$("#questionInput").focus()});
$("#categoryRow").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;$$('.category-row button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.category=b.dataset.category});
async function analyzeUploadedImage(){const button=$("#questionForm button[type=submit]"),label=$("#submitModeLabel"),endpoint=window.TAROT_VISION_ENDPOINT||"/api/vision-reading";button.disabled=true;label.textContent="Codex 正在解析…";$("#questionHint").textContent="Codex 正在结合你的问题、牌位与正逆位生成完整解析";try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agent:"codex",question:state.question,image:{mime:state.imageMime,data:state.imageData.split(',')[1]},expected:{deck:"Rider-Waite-Smith",return:"cards and grounded Codex analysis"}})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`识别服务返回 ${response.status}`);const recognized=(result.cards||[]).slice(0,10).map((item,index)=>{const card=Number.isInteger(item.id)?cards[item.id]:cards.find(c=>c.name===item.name||c.en===item.name);if(!card)throw new Error(`无法匹配牌面：${item.name||`第 ${index+1} 张`}`);return{card,reversed:Boolean(item.reversed),position:String(item.position||`第 ${index+1} 张`).slice(0,40)}});if(!recognized.length)throw new Error("没有识别出清晰的塔罗牌");state.visionCards=recognized;state.drawn=recognized.map(item=>({card:item.card,reversed:item.reversed}));state.selected=state.drawn.map(d=>d.card.id);state.sequences=state.drawn.map((_,i)=>i+1);state.drawTime=new Date();const suggested=result.spreadKey&&spreads[result.spreadKey]&&spreads[result.spreadKey].positions.length===recognized.length?spreads[result.spreadKey]:null;state.spread=suggested||{name:"图片牌阵",description:"依据上传图片的空间布局",positions:recognized.map(item=>escapeHtml(item.position))};renderResult();renderCodexAnalysis(result.analysis);$("#interpretation").hidden=false;$("#readingActions").hidden=true;saveReading(true);showScreen("result")}catch(error){$("#questionHint").textContent=`未能读取图片：${error.message}`;toast("图片解析失败，请重试")}finally{button.disabled=false;label.textContent="进入仪式"}}
$("#questionForm").addEventListener("submit",async e=>{e.preventDefault();const q=$("#questionInput").value.trim();if(q.length>0&&q.length<4){toast("问题可以留空；如果填写，请写得更完整一些");return}if(!q&&!state.imageData){toast("请写下问题，或上传一张牌阵图片");return}state.question=q||"未填写问题 · 图片牌阵解析";if(!$(".category-row button.selected"))state.category=q?inferCategory(q):"general";state.spread=spreads[state.category];if(state.imageData){await analyzeUploadedImage();return}$("#questionEcho").textContent=`“${q}”`;showScreen("shuffle");startShuffle()});

function prepareImageReading(){const provider=agentProviders.codex;state.agent="codex";$("#imageAnalysisPreview").src=state.imageData;$("#imageQuestionEcho").textContent=state.question==="未填写问题 · 图片牌阵解析"?"没有预设问题，Codex 将只依据牌面与空间布局给出开放式解读。":`“${state.question}”`;$("#visionAgentLabel").textContent=`默认解析 Agent · ${provider.label}`;$("#visionStatus").textContent="Codex 将先读取牌名、正逆位与空间布局，识别后由你确认。";$("#visionResult").hidden=true;$("#startVisionAnalysis").hidden=false;showScreen("image")}
$("#backFromImage").addEventListener("click",()=>showScreen("question"));
function renderVisionConfirmation(result){const recognized=(result.cards||[]).slice(0,10).map((item,index)=>{const card=Number.isInteger(item.id)?cards[item.id]:cards.find(c=>c.name===item.name||c.en===item.name);return{card:card||cards[0],reversed:Boolean(item.reversed),position:item.position||`第 ${index+1} 张`}});if(!recognized.length)throw new Error("视觉接口没有返回可确认的牌面");state.visionCards=recognized;const exact=Object.entries(spreads).filter(([,spread])=>spread.positions.length===recognized.length);const suggested=result.spreadKey&&spreads[result.spreadKey]?result.spreadKey:exact[0]?.[0]||"general";$("#recognizedSpread").innerHTML=exact.length?exact.map(([key,spread])=>`<option value="${key}" ${key===suggested?'selected':''}>${spread.name} · ${spread.positions.length} 张</option>`).join(''):`<option value="custom">图片布局 · ${recognized.length} 张</option>`;const options=cards.map(card=>`<option value="${card.id}">${card.name} · ${card.en}</option>`).join('');$("#recognizedCards").innerHTML=recognized.map((item,index)=>`<div class="recognized-card"><span>${index+1}</span><select data-card-index="${index}">${options.replace(`value="${item.card.id}"`,`value="${item.card.id}" selected`)}</select><label><input type="checkbox" data-reversed-index="${index}" ${item.reversed?'checked':''}> 逆位</label></div>`).join('');$("#visionResult").hidden=false;$("#startVisionAnalysis").hidden=true;$("#visionStatus").textContent=`已识别 ${recognized.length} 张牌。请核对牌名、正逆位和牌阵，再进入解析。`}
$("#startVisionAnalysis").addEventListener("click",async()=>{const endpoint=window.TAROT_VISION_ENDPOINT||"/api/vision-reading";const button=$("#startVisionAnalysis");button.disabled=true;button.firstChild.textContent="正在识别… ";$("#visionStatus").textContent="Codex 正在识别牌名、正逆位和空间布局，通常需要几十秒…";try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agent:"codex",question:state.question,image:{mime:state.imageMime,data:state.imageData.split(',')[1]},expected:{deck:"Rider-Waite-Smith",return:"spreadKey, cards[{name,reversed,position}], confidence"}})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`识别服务返回 ${response.status}`);renderVisionConfirmation(result)}catch(error){$("#visionStatus").textContent=`识别没有完成：${error.message}。图片尚未进入解读，请稍后重试。`;toast("Codex 图片识别失败") }finally{button.disabled=false;button.firstChild.textContent="开始 Codex 识别 "}});
$("#confirmVisionResult").addEventListener("click",()=>{const selectors=$$("#recognizedCards select"),reversed=$$("#recognizedCards input[type=checkbox]");state.drawn=selectors.map((select,index)=>({card:cards[+select.value],reversed:reversed[index].checked}));state.selected=state.drawn.map(d=>d.card.id);state.sequences=state.drawn.map((_,i)=>i+1);state.drawTime=new Date();const spreadKey=$("#recognizedSpread").value;if(spreadKey==='custom'){state.spread={name:"图片牌阵",description:"依据上传图片的空间顺序",positions:state.visionCards.map((x,i)=>escapeHtml(String(x.position||`第 ${i+1} 张`)).slice(0,40))}}else state.spread=spreads[spreadKey];renderResult();saveReading(false);showScreen("result")});

function buildShuffle(){const deck=$("#shuffleDeck");deck.innerHTML=Array.from({length:12},(_,i)=>`<div class="shuffle-card" style="--i:${i}"></div>`).join("")}
function startShuffle(){buildShuffle();let round=1,elapsed=0;const labels=["第一遍 · 放下预设","第二遍 · 回到直觉","第三遍 · 接收启示"];$("#roundNumber").textContent=round;$("#ritualText").textContent=labels[0];$("#ritualProgress").style.width="0%";clearInterval(startShuffle.timer);startShuffle.timer=setInterval(()=>{elapsed+=100;const within=(elapsed%2200)/2200;$("#ritualProgress").style.width=`${within*100}%`;const next=Math.min(3,Math.floor(elapsed/2200)+1);if(next!==round){round=next;$("#roundNumber").textContent=round;$("#ritualText").textContent=labels[round-1]}if(elapsed>=6600){clearInterval(startShuffle.timer);$("#ritualProgress").style.width="100%";setTimeout(prepareSelection,450)}},100)}
function prepareSelection(){showScreen("select");state.selected=[];state.sequences=[];$("#neededCount").textContent=state.spread.positions.length;$("#spreadName").textContent=state.spread.name;$("#spreadDescription").textContent=state.spread.description;renderFan();renderSequenceInputs();updateSelection()}
function seededPool(){const ids=Array.from({length:cards.length},(_,i)=>i);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return ids}
function renderFan(){const pool=seededPool();const fan=$("#cardFan");const spacing=Math.max(3.8,(fan.clientWidth-92)/(pool.length-1));fan.innerHTML=pool.map((id,i)=>{const centered=i-(pool.length-1)/2;const normalized=centered/((pool.length-1)/2);const x=centered*spacing;const r=normalized*24;const y=Math.pow(Math.abs(normalized),1.7)*62;return `<button class="fan-card" data-card="${id}" data-sequence="${i+1}" style="--x:${x}px;--r:${r}deg;--y:${y}px;--layer:${i}" aria-label="选择序号 ${i+1}，共 ${pool.length} 张"><span class="tarot-back"></span></button>`}).join("")}
function renderSequenceInputs(){const count=state.spread.positions.length;$("#numberDrawHint").textContent=`请从 1—78 中输入 ${count} 个不重复数字`;$("#sequenceInputs").innerHTML=Array.from({length:count},(_,i)=>`<label><span>第 ${i+1} 张</span><input type="number" min="1" max="78" inputmode="numeric" aria-label="第 ${i+1} 张牌的序列号" placeholder="1—78"></label>`).join("")}
function syncSequenceInputs(){$$("#sequenceInputs input").forEach((input,i)=>input.value=state.sequences[i]||"")}
function paintSelection(sync=true){$$('.fan-card').forEach(x=>{const n=state.selected.indexOf(+x.dataset.card);x.classList.toggle('selected',n>=0);if(n>=0)x.dataset.order=String(+x.dataset.sequence).padStart(2,'0');else delete x.dataset.order});if(sync)syncSequenceInputs();updateSelection()}
$("#cardFan").addEventListener("click",e=>{const b=e.target.closest(".fan-card");if(!b)return;const id=+b.dataset.card,sequence=+b.dataset.sequence;const index=state.selected.indexOf(id);if(index>=0){state.selected.splice(index,1);state.sequences.splice(index,1)}else if(state.selected.length<state.spread.positions.length){state.selected.push(id);state.sequences.push(sequence)}else return;paintSelection()});
$("#applySequenceNumbers").addEventListener("click",()=>{const inputs=$$("#sequenceInputs input"),numbers=inputs.map(input=>Number(input.value));if(numbers.some(n=>!Number.isInteger(n)||n<1||n>78)){toast(`请完整输入 ${inputs.length} 个 1—78 的数字`);return}if(new Set(numbers).size!==numbers.length){toast("每个序列号只能选择一次");return}const selectedButtons=numbers.map(n=>$(`.fan-card[data-sequence="${n}"]`));if(selectedButtons.some(button=>!button)){toast("没有找到对应序列号，请重新洗牌");return}state.sequences=numbers;state.selected=selectedButtons.map(button=>+button.dataset.card);paintSelection(false);toast(`已按序列号选中 ${numbers.length} 张牌`)});
$("#sequenceInputs").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();$("#applySequenceNumbers").click()}});
function updateSelection(){const n=state.spread.positions.length;$("#selectionCount").textContent=`78 张中已选 ${state.selected.length} / ${n}`;$("#revealButton").disabled=state.selected.length!==n}
$("#resetSelection").addEventListener("click",()=>{state.selected=[];state.sequences=[];paintSelection()});
$("#revealButton").addEventListener("click",()=>{state.drawTime=new Date();state.drawn=state.selected.map(id=>({card:cards[id],reversed:Math.random()<.35}));renderResult();saveReading(false);showScreen("result")});
function renderResult(){const provider=agentProviders.codex;state.agent="codex";$("#resultQuestion").textContent=`“${state.question}” · ${state.spread.name}`;$("#resultAgent").textContent=`默认解析 Agent · ${provider.label}`;$("#resultAgent").classList.remove('is-fallback');$("#spreadBoard").innerHTML=state.drawn.map((d,i)=>`<div class="drawn-position" style="--i:${i}"><div class="drawn-card has-art ${d.reversed?'reversed':''}" role="img" aria-label="${d.card.name}${d.reversed?'逆位':'正位'}牌面" style="--card-image:url('${cardImageUrl(d.card)}')"></div><span class="position-label">${escapeHtml(String(state.spread.positions[i]||`第 ${i+1} 张`))}</span><span class="orientation">${d.reversed?'逆位':'正位'}</span></div>`).join("");$("#shareReadingButton").hidden=false;$("#sharePanel").hidden=true;$("#readingActions").hidden=false;$("#interpretation").hidden=true}
const topicGuidance={
  love:{focus:"关系中的真实需求、互动边界与双方节奏",action:"在24小时内把一个猜测改写成可以直接确认的问题",steps:["写下你真正想确认的一件事，不同时追问多个答案","先描述事实和感受，再提出一个具体、可回答的请求","给对方回应空间，同时为自己设定等待边界","根据真实回应决定下一步，不用沉默替对方作答"]},
  career:{focus:"可调动的能力、现实资源与下一步职业行动",action:"今天确定一个可交付成果，并预约第一次外部反馈",steps:["写下一句话目标：面向谁、证明哪项能力、何时交付","只保留最能证明目标的2—3项材料，其余放入候选区","先完成文字和结构，再处理视觉细节","在截止前预留一次反馈、一次校对和一次真实投递"]},
  finance:{focus:"现金流、现实资源、风险边界与可持续积累",action:"今天记录一项可确认的收入、支出或资源事实，再决定下一步",steps:["列出目前已经确认的收入、固定支出和可用资源","标出最可能造成压力的一项变量，不用乐观假设填补空缺","设置一个明确的金额或时间边界，先保护基本盘","七天后根据真实流水复盘，不把塔罗结果作为投资买卖依据"]},
  study:{focus:"学习基础、理解方式、执行节奏与可验证进步",action:"今天完成一次25分钟专注学习，并用五分钟无提示复述",steps:["把目标改写成今天能检查的知识点或题量","先测试当前掌握程度，再把时间放到真正薄弱处","完成一轮输出练习：做题、复述或写出结构","在考试或截止前安排一次模拟，并依据错误类型调整"]},
  choice:{focus:"两条路径各自的代价、收益与不可妥协项",action:"今天为两个选项各写三项代价，并圈出你愿意长期承担的一组",steps:["分别写下两个选项一年后的日常，而不只写理想结果","列出各自最坏但可承受的代价","用同一组标准评分，避免一边看收益、一边只看风险","先做一个可撤回的小实验，再根据新事实决定"]},
  timing:{focus:"事情所处阶段、推进条件与时间窗口",action:"今天确认一个能观察进展的里程碑，并为它设定复查日期",steps:["定义你说的“发生”或“完成”具体指什么","列出当前已经具备和仍然缺少的条件","只推进最近的一个里程碑，不把趋势当作确定日期","到复查日依据新事实更新判断，而不是反复追问时间"]},
  self:{focus:"内在模式、尚未承认的需要与可持续成长",action:"今晚记录一次触发事件，并把评价句改写成需要句",steps:["写下已经发生的事实，不加入对自己的评价","辨认你在保护什么，以及真正需要什么","选择一个十五分钟内可以完成的照顾动作","三天后复盘它是否降低了消耗，而不是要求立刻变好"]},
  general:{focus:"当下局势的主要动力、盲点与可控出口",action:"今天结束前完成一个十五分钟内能闭环的小动作",steps:["把问题改写成一个可以观察的结果","区分已知事实、个人解释和仍待验证的信息","先完成最小闭环，再决定是否扩大投入","在下一次行动后依据新事实复盘一次"]}
};
const suitMeta={"权杖":{element:"火",gift:"行动与创造",shadow:"急躁或能量透支"},"圣杯":{element:"水",gift:"感受与连接",shadow:"情绪淹没事实"},"宝剑":{element:"风",gift:"判断与沟通",shadow:"过度分析或冲突"},"星币":{element:"土",gift:"现实资源与积累",shadow:"僵化或只看短期得失"}};
const classicPairs={"死神|星星":"结束之后出现疗愈与重建空间","高塔|星星":"旧结构崩解后，真正的希望才有落点","死神|审判":"旧方向结束，必须重新回答自己真正要什么","月亮|太阳":"暧昧与投射逐渐被事实照亮","恶魔|力量":"需要驯化欲望，而不是压抑或纵容它","女祭司|魔术师":"直觉已经出现，下一步是把它转成行动","隐者|恋人":"独处与连接互相拉扯，需要重新协商距离","皇帝|命运之轮":"控制感正在接受变化的测试","正义|命运之轮":"过去的选择正在与时机形成回响","高塔|宝剑十":"旧结构已经走到必须结束的位置"};
function getSuit(card){return Object.keys(suitMeta).find(s=>card.name.startsWith(s))||null}
function getRank(card){if(card.id<22)return null;return (card.id-22)%14+1}
function tarotStats(){const majors=state.drawn.filter(d=>d.card.id<22).length,reversed=state.drawn.filter(d=>d.reversed).length,suits={};state.drawn.forEach(d=>{const suit=getSuit(d.card);if(suit)suits[suit]=(suits[suit]||0)+1});return{majors,reversed,suits}}
function questionContext(){const q=state.question,rawDeadline=(q.match(/((?:本|下|这)?(?:周末|月底|年底|月末)|\d{1,2}[月\/.-]\d{1,2}[日号]?|\d{1,2}[日号](?:前|之前)|十一(?:前|之前))/)||[])[1],deadline=rawDeadline?/(?:前|之前)$/.test(rawDeadline)?rawDeadline:`${rawDeadline}前`:"你设定的时间点前";let target="这件事";let criteria=["目标是否足够清楚","现有条件是否支持目标","是否留出了验证与调整空间"];if(/简历|作品集/.test(q)){target=/简历/.test(q)&&/作品集/.test(q)?"简历与作品集":/作品集/.test(q)?"作品集":"简历";criteria=["目标岗位最看重的三项能力是否清楚","材料是否用问题—行动—结果证明能力","是否已经经过一次外部视角的删改"]}else if(/面试|求职|投递/.test(q)){target="求职准备";criteria=["岗位与自身证据是否匹配","表达是否具体且可验证","是否已经进行模拟和反馈"]}else if(/财运|财务|收入|工资|存款|金钱|资金|债务|预算/.test(q)){target="当前财务安排";criteria=["已确认的现金流是否清楚","风险边界是否可承受","决定是否基于真实数据而非期待"]}else if(/学习|学业|考试|论文|课程|成绩|复习/.test(q)){target="学习目标";criteria=["目标是否具体到知识点或成果","练习是否包含主动输出","是否根据错误证据调整方法"]}else if(/关系|感情|复合|喜欢|对方/.test(q)){target="这段关系";criteria=["真实互动是否支持你的判断","双方需求是否被清楚表达","边界与节奏是否可持续"]}else if(/选择|还是|要不要|是否/.test(q)){target="这个选择";criteria=["两个选项是否使用同一标准比较","最坏代价是否可承受","是否能先做低风险实验"]}return{deadline,target,criteria,yesNo:/能否|是否|会不会|可不可以|能不能/.test(q)}}
function timeFactor(){const h=state.drawTime?.getHours?.()??12;return h<6?"night":h<12?"morning":h<18?"afternoon":"evening"}
function readingSeed(){const raw=`${state.question}|${state.sequences.join(',')}|${state.drawTime?.toISOString?.().slice(0,16)||''}`;let hash=2166136261;for(let i=0;i<raw.length;i++){hash^=raw.charCodeAt(i);hash=Math.imul(hash,16777619)}return hash>>>0}
function lensFor(index,reversed){const position=state.spread.positions[index]||"这个位置";const last=index===state.drawn.length-1;const base=last?"门｜把牌意转成可执行的出口":/阻力|盲点|未被看见/.test(position)?"窗户｜看见容易漏掉的条件":index===0?"镜子｜核对你真正身处的状态":"锚｜找到正在固定局面的核心";return reversed?`${base}；逆位在这里表现为能量的${["阻塞","过度","内化","延迟"][state.drawn[index].card.id%4]}`:base}
const suitApplications={
  career:{权杖:"推进速度与项目取舍",圣杯:"个人认同、受众感受与反馈关系",宝剑:"信息结构、文字判断与编辑标准",星币:"现有素材、技能证据与可交付程度"},
  finance:{权杖:"开源动力与资源投入速度",圣杯:"消费背后的情绪需要",宝剑:"财务判断、条款与风险信息",星币:"现金流、资产基础与长期积累"},
  study:{权杖:"学习动力与执行节奏",圣杯:"兴趣、压力与情绪承载",宝剑:"理解、表达与考试策略",星币:"基础练习、时间投入与稳定进步"},
  love:{权杖:"主动靠近的方式与关系热度",圣杯:"真实感受与情感回应",宝剑:"沟通方式、假设与边界",星币:"承诺能否落实到稳定行动"},
  choice:{权杖:"你愿意投入的行动强度",圣杯:"哪个选择更贴近真实需要",宝剑:"判断标准与信息质量",星币:"成本、资源与长期可持续性"},
  timing:{权杖:"启动速度与推进窗口",圣杯:"关系或情绪条件何时成熟",宝剑:"信息清晰度与决策时点",星币:"现实条件与可观察里程碑"},
  self:{权杖:"恢复行动感与生命力",圣杯:"承认感受而不被感受淹没",宝剑:"调整自我叙事与判断方式",星币:"建立能长期坚持的现实习惯"},
  general:{权杖:"行动与优先级",圣杯:"感受与关系",宝剑:"判断与沟通",星币:"资源与落地"}
};
const majorApplications=["先允许一个不完美但真实的开始","盘点你已经拥有的工具，并主动使用","在行动前保留观察和核对信息的空间","让成果被持续滋养，而不是一次耗尽","用清楚的结构、边界和顺序稳定局面","借助可靠方法或有经验者的反馈","先确认价值一致，再作选择","把分散的力量收回同一主线","用稳定节奏代替硬撑和自我攻击","短暂退出噪音，独立辨认真正标准","接受变量，并为变化预留缓冲","以事实和统一标准作出判断","暂停无效用力，换角度删减","结束已经失效的部分，为新结构腾位","控制剂量与节奏，让不同部分协同","识别让你失去选择权的执念","旧结构需要被打破，避免继续粉饰","回到真实愿景，以小步恢复信心","先验证信息，不在焦虑中补完故事","让成果公开接受现实检验","停止自责，用复盘回应真正召唤","完成最后闭环，再进入下一阶段"];
function cardApplication(d){if(d.card.id<22)return majorApplications[d.card.id];const suit=getSuit(d.card),rank=getRank(d.card),topic=suitApplications[state.category]||suitApplications.general;const phase=rank<=2?"先定义起点和选择":rank<=4?"把初步成果整理成结构":rank<=7?"处理冲突并重新校准":rank<=10?"推动收尾，防止临近完成时过载":rank===11?"以学习者姿态收集新信息":rank===12?"控制推进速度，不要用冲刺代替方向":rank===13?"稳定承载并完善细节":"承担决策责任并建立标准";return `${topic[suit]}是这一张牌落到问题中的焦点；${phase}`}
function cardContext(d,index){const suit=getSuit(d.card),position=state.spread.positions[index],meaning=d.reversed?d.card.reversed:d.card.upright,ctx=questionContext();let deep="";if(d.card.id<22){const stage=d.card.id<=7?"身份与行动":d.card.id<=14?"内在修正":"阴影、疗愈与整合";deep=`它位于愚人之旅的“${stage}”阶段：${cardApplication(d)}。`}else{const meta=suitMeta[suit];deep=`${suit}属${meta.element}元素。放在“${position}”，它把注意力落到${cardApplication(d)}；需要防止${meta.shadow}。`}const reversal=d.reversed?`逆位不是简单的“坏结果”，而是在提醒：${cardApplication(d)}这股能量可能被卡住、用过头，或尚未向外落实。`:"正位说明这股能量目前较容易被直接使用，但仍需要现实行动承接。";return `<div class="card-reading"><div class="reading-title"><span>${String(index+1).padStart(2,'0')}</span><strong>${position}｜${d.card.name}${d.reversed?' · 逆位':' · 正位'}</strong></div><p><b>关键词</b>${meaning}</p><p><b>对应问题</b>关于“${ctx.target}”，${cardApplication(d)}。${reversal}</p><p><b>位置透镜</b>${lensFor(index,d.reversed)}。${deep}</p></div>`}
function pairRelation(a,b){const names=[a.card.name,b.card.name];for(const [key,text] of Object.entries(classicPairs)){const pair=key.split('|');if(pair.every(n=>names.includes(n)))return `经典组合：${text}`;}const sa=getSuit(a.card),sb=getSuit(b.card);if(a.card.id<22&&b.card.id<22){const direction=a.card.id<b.card.id?"递进":"回头补课";return `两张大阿尔卡纳形成${direction}关系：前一张提出课题，后一张把它推进到更深层。`;}if(sa&&sb){if(sa===sb)return `${sa}连续出现，${suitMeta[sa].gift}成为主导力量。`;const friendly=[["权杖","宝剑"],["圣杯","星币"]].some(x=>x.includes(sa)&&x.includes(sb));const tense=[["权杖","圣杯"],["宝剑","星币"]].some(x=>x.includes(sa)&&x.includes(sb));if(friendly)return `${suitMeta[sa].element}与${suitMeta[sb].element}互相助长，想法较容易转成结果。`;if(tense)return `${suitMeta[sa].element}与${suitMeta[sb].element}存在张力，需要避免一个维度压住另一个维度。`;if(getRank(a.card)===getRank(b.card))return `同数字跨花色共振，说明你正从不同层面经历同一个发展阶段。`;}return `前牌描述局势，后牌回应如何承接；两者构成“原因—反应”的对话。`}
function directionalScore(){const weights=state.drawn.map((_,i)=>1+i/(state.drawn.length-1||1)*.45);const total=state.drawn.reduce((sum,d,i)=>{let value=d.reversed?-.55:.6;if(d.card.id<22)value+=d.reversed?-.12:.12;if(i===state.drawn.length-1)value+=d.reversed?-.18:.18;return sum+value*weights[i]},0);return total/weights.reduce((a,b)=>a+b,0)}
function verdictText(score,ctx){if(score>.38)return `整体趋势偏支持：${ctx.target}有机会在${ctx.deadline}推进到“可以使用、可以接受反馈”的版本；关键不是继续扩充，而是尽快确定主线并主动取舍。`;if(score>-.12)return `这是一个有条件的“可以”：${ctx.target}并非做不到，但现有节奏还不足以自动抵达结果。能否赶上${ctx.deadline}，主要取决于你是否立刻收缩范围、建立完成标准并引入外部反馈。`;return `按当前能量，${ctx.target}在${ctx.deadline}容易因阻力、反复修改或范围失控而延期。牌面不是否定能力，而是在建议你重设范围：先交付最小可用版本，再决定是否扩充。`}
function relationModel(a,b){const sa=getSuit(a.card),sb=getSuit(b.card);if(a.card.id<22&&b.card.id<22)return a.card.id<b.card.id?"递进 · A1 愚人之旅":"回补 · A1 愚人之旅";if(sa&&sb&&sa===sb)return "递进 · A2 同花色数字旅程";if(sa&&sb&&getRank(a.card)===getRank(b.card))return "对话 · B3 数字共振";if(sa&&sb)return "对话 · A3 元素牌性";return "转折 · 牌位承接"}
function actionPlan(ctx,score){const steps=[...topicGuidance[state.category].steps];if(score<-.12)steps[0]=`今天先定义“最小可用版”：删除至少三分之一非必要内容，只保留能支撑${ctx.target}的核心`;else if(score>.38)steps[0]=`今天确定${ctx.target}的唯一主线，并把完成标准写成三条可检查的句子`;return `<ol class="action-plan">${steps.map((step,i)=>`<li><span>${["今天","下一阶段","反馈轮","截止前"][i]}</span><p>${step}</p></li>`).join('')}</ol>`}
function tarotInterpretation(){const stats=tarotStats(),total=state.drawn.length,majorRatio=stats.majors/total,ctx=questionContext(),score=directionalScore();const suitEntries=Object.entries(stats.suits).sort((a,b)=>b[1]-a[1]),dominant=suitEntries[0];const level=majorRatio>.5?"大阿尔卡纳超过一半，问题牵涉身份、方向或阶段转换":majorRatio>=.3?"大牌与小牌并行，外部时机与个人选择共同作用":"小阿尔卡纳主导，这更像一个可以通过日常取舍和项目管理改变的局面";const suitLine=dominant?`${dominant[0]}最集中，${suitMeta[dominant[0]].gift}是主要动力`:"元素没有明显集中，需要同时照顾行动、感受、判断与现实资源";const cardsHtml=state.drawn.map(cardContext).join('');const relations=state.drawn.slice(0,-1).map((d,i)=>`<li><strong>${d.card.name} → ${state.drawn[i+1].card.name}<em>${relationModel(d,state.drawn[i+1])}</em></strong><span>${pairRelation(d,state.drawn[i+1])}</span></li>`).join('');const first=state.drawn[0],middle=state.drawn[Math.floor(total/2)],last=state.drawn[total-1],energy=score>.38?"清晰推进":score>-.12?"收束校准":"减负重构";const rows=state.drawn.map((d,i)=>`<tr><td>${state.spread.positions[i]}</td><td>${d.card.name}</td><td>${d.reversed?'逆位':'正位'}</td></tr>`).join('');return `<section class="reading-section verdict"><span class="section-kicker">整体判断</span><h3>${verdictText(score,ctx)}</h3><p>${level}；${suitLine}。${stats.reversed}张逆位不等于失败，而是指出最可能发生返工、拖延或过度用力的位置。</p></section><section class="reading-section"><h3>牌阵</h3><div class="reading-table-wrap"><table class="reading-table"><thead><tr><th>位置</th><th>牌面</th><th>状态</th></tr></thead><tbody>${rows}</tbody></table></div><div class="method-note">韦特体系 · 用户手选序号 ${state.sequences.map(n=>String(n).padStart(2,'0')).join(' / ')} · seed ${readingSeed()} · time_factor ${timeFactor()}<br>seed 为本次记录的复现键；牌面来自用户手选，并非由脚本代抽。</div></section><section class="reading-section"><h3>逐牌解析</h3>${cardsHtml}</section><section class="reading-section"><h3>牌间关系</h3><ul class="relation-list">${relations}</ul><p class="relation-summary"><b>关系结论</b>${first.card.name}给出起点，${middle.card.name}把问题聚焦到“${cardApplication(middle)}”，而${last.card.name}${last.reversed?'以逆位形成提醒：不要用失速或反复推翻来回应压力':'把前面的张力导向一个可以主动承接的出口'}。这组牌的主导因素是过程、结构与选择效率，而不是能力不足。</p></section><section class="reading-section narrative"><h3>综合解读</h3><p><b>起点</b>${first.card.name}显示你并非从零开始，真正要核对的是：现有投入是否服务于同一个目标。</p><p><b>张力</b>${middle.card.name}把矛盾集中在“${middle.reversed?middle.card.reversed:middle.card.upright}”。请用三个标准检查：${ctx.criteria.join('；')}。</p><p><b>转折</b>${last.card.name}${last.reversed?'逆位提示最危险的不是慢，而是焦虑下突然扩充、推翻或同时重做多件事':'正位说明方向已经可见，下一步要让它进入日程，而不是继续停留在想法中'}。</p><p><b>出口</b>${topicGuidance[state.category].action}。</p><p><b>回响</b>完成后只收集“哪里看不懂、哪里证据不足、哪里重点不突出”三类反馈，不把一次反馈理解成对自我价值的判断。</p></section><section class="reading-section"><h3>${ctx.deadline}的行动出口</h3>${actionPlan(ctx,score)}</section><section class="reading-section closing"><h3>能量总结：${energy}</h3><p>牌显示的是当下能量，你的选择随时可以改变走向。此刻最值得你回答的问题是：为了按时完成，你愿意先放弃哪个“必须做到非常完美”的标准？</p></section>`}

const trigramDefs=[
  {name:"坤",nature:"地",element:"土",bits:[0,0,0],image:"承载、顺势与长期养成"},
  {name:"乾",nature:"天",element:"金",bits:[1,1,1],image:"主动、原则与创造"},
  {name:"兑",nature:"泽",element:"金",bits:[1,1,0],image:"交流、喜悦与兑现"},
  {name:"离",nature:"火",element:"火",bits:[1,0,1],image:"看见、依附与明辨"},
  {name:"震",nature:"雷",element:"木",bits:[1,0,0],image:"启动、惊动与迅速行动"},
  {name:"巽",nature:"风",element:"木",bits:[0,1,1],image:"渗透、协商与渐进影响"},
  {name:"坎",nature:"水",element:"水",bits:[0,1,0],image:"风险、深度与反复考验"},
  {name:"艮",nature:"山",element:"土",bits:[0,0,1],image:"停止、边界与沉淀"}
];
const trigramByNumber=n=>trigramDefs[n%8];
const trigramByBits=bits=>trigramDefs.find(g=>g.bits.join('')===bits.join(''));
const hexagramNames=[
  ["坤","泰","临","明夷","复","升","师","谦"],
  ["否","乾","履","同人","无妄","姤","讼","遁"],
  ["萃","夬","兑","革","随","大过","困","咸"],
  ["晋","大有","睽","离","噬嗑","鼎","未济","旅"],
  ["豫","大壮","归妹","丰","震","恒","解","小过"],
  ["观","小畜","中孚","家人","益","巽","涣","渐"],
  ["比","需","节","既济","屯","井","坎","蹇"],
  ["剥","大畜","损","贲","颐","蛊","蒙","艮"]
];
const hexThemes={乾:"主动开创，但以自律守住方向",坤:"先承载现实，让事情自然成形",屯:"开端艰难，宜建立秩序而非急于求成",蒙:"信息不足，先学习并寻找可靠指引",需:"条件尚未成熟，等待不是停滞而是准备",讼:"立场冲突，宜厘清边界并减少正面消耗",师:"需要组织资源、纪律与清晰分工",比:"通过可信任的连接获得支持",小畜:"力量尚小，先积累资源与影响",履:"谨慎行事，尊重规则与位置",泰:"上下相通，适合推动合作",否:"沟通闭塞，先停止无效消耗",同人:"求同存异，以共同目标联合",大有:"资源充足，更要承担使用资源的责任",谦:"降低姿态，实力会因此更稳定",豫:"动力正在酝酿，先把准备做足",随:"顺应真实变化，不等于放弃原则",蛊:"旧问题需要整顿、修复与负责",临:"机会正在靠近，需要亲自参与",观:"先观察全局，再决定介入方式",噬嗑:"必须处理明确障碍，不能继续含糊",贲:"形式可以优化，但不要掩盖实质",剥:"旧结构逐层脱落，宜减少投入",复:"回到起点，重新建立正确节奏",无妄:"以真实和正当行动，避免投机",大畜:"蓄势、训练与延迟满足",颐:"审视你在滋养什么，也审视信息入口",大过:"负荷已经过重，需要改变支撑方式",坎:"风险反复出现，靠稳定流程穿越",离:"让事实被看见，同时避免过度依附",咸:"相互感应，关系会因回应而变化",恒:"长期一致比短期激情更重要",遁:"主动后退，保存实力与边界",大壮:"力量很强，越需要克制使用",晋:"进展清晰，适合稳步向前",明夷:"环境不利，暂时隐藏锋芒",家人:"内部秩序和角色边界需要明确",睽:"分歧真实存在，从小共识开始",蹇:"道路受阻，宜求助并调整路线",解:"压力开始松动，及时解决遗留问题",损:"主动减少，换取更重要的空间",益:"资源增长，适合投入有复利的事情",夬:"到了清楚决断、公开边界的时刻",姤:"突然而来的相遇或变量，不宜过早承诺",萃:"人和资源聚集，关键在共同中心",升:"循序上升，积小步成大势",困:"外部受限，先守住内在秩序",井:"基础资源一直都在，问题是如何取用",革:"旧方式已经失效，需要有条件地变革",鼎:"更新结构，把新秩序稳定下来",震:"变化突然启动，先稳住再行动",艮:"到该停止的位置，边界本身就是答案",渐:"缓慢但可靠，遵循正确顺序",归妹:"位置与时机未必匹配，避免仓促定局",丰:"成果放大，也要防止盛极而衰",旅:"处在过渡期，保持轻装与适应",巽:"持续而柔和地影响局面",兑:"通过真诚交流形成连接与兑现",涣:"旧的凝聚正在松散，需要重新聚焦",节:"用清晰限制保护长期发展",中孚:"诚信与内外一致是关键",小过:"小事可为，大动作宜谨慎",既济:"表面完成后仍需防止松懈",未济:"尚未完成，最后阶段更考验秩序"};
function hexagramFromLines(lines){const lower=trigramByBits(lines.slice(0,3)),upper=trigramByBits(lines.slice(3,6));return{name:hexagramNames[trigramDefs.indexOf(upper)][trigramDefs.indexOf(lower)],upper,lower,lines}}
function lineDiagram(lines,moving=0){return `<div class="gua-lines">${[...lines].reverse().map((line,i)=>`<i class="${line?'yang':'yin'} ${6-i===moving?'moving':''}"><span></span><span></span></i>`).join('')}</div>`}
function guaCard(label,gua,moving=0){return `<div class="gua-card"><span>${label}</span>${lineDiagram(gua.lines,moving)}<strong>${gua.name}卦</strong><small>${gua.upper.name}${gua.upper.nature}上 · ${gua.lower.name}${gua.lower.nature}下</small></div>`}
function bodyUseReading(original,moving){const body=moving<=3?original.upper:original.lower,use=moving<=3?original.lower:original.upper;const generates={木:"火",火:"土",土:"金",金:"水",水:"木"},controls={木:"土",土:"水",水:"火",火:"金",金:"木"};let relation="比和",meaning="双方属性相同，成败更看节奏与持续性";if(generates[use.element]===body.element){relation="用生体";meaning="外部条件对你有助力，可以主动承接"}else if(generates[body.element]===use.element){relation="体生用";meaning="你正在向事情持续输出，需要控制消耗"}else if(controls[use.element]===body.element){relation="用克体";meaning="外部压力较强，先稳住自身再应对"}else if(controls[body.element]===use.element){relation="体克用";meaning="局面有机会被你掌控，但需要付出执行成本"}return{body,use,relation,meaning}}
function calculatePlum(){const seq=state.sequences.length?state.sequences:state.selected.map(id=>id+1),t=state.drawTime;const first=seq[0]||1,second=seq[1]||1,moving=(seq.reduce((a,b)=>a+b,0)+t.getHours()+t.getMinutes())%6||6;const upper=trigramByNumber(first),lower=trigramByNumber(second),lines=[...lower.bits,...upper.bits],original=hexagramFromLines(lines);const mutual=hexagramFromLines([lines[1],lines[2],lines[3],lines[2],lines[3],lines[4]]);const changedLines=[...lines];changedLines[moving-1]=changedLines[moving-1]?0:1;const changed=hexagramFromLines(changedLines);return{seq,first,second,moving,original,mutual,changed,bodyUse:bodyUseReading(original,moving),time:t}}
function plumInterpretation(){const p=calculatePlum(),time=`${String(p.time.getHours()).padStart(2,'0')}:${String(p.time.getMinutes()).padStart(2,'0')}`;return `<section class="reading-section"><h3>数起卦依据</h3><p>取第一张铺牌序号 <b>${String(p.first).padStart(2,'0')}</b> 为上卦数，第二张序号 <b>${String(p.second).padStart(2,'0')}</b> 为下卦数；全部序号 ${p.seq.map(n=>String(n).padStart(2,'0')).join('、')} 与抽牌时刻 ${time} 合参，得第 <b>${p.moving}</b> 爻动。</p><div class="method-note">此处只读取铺牌序号与时间，不读取任何塔罗牌名、牌义或正逆位</div></section><div class="gua-grid">${guaCard('本卦 · 当下',p.original,p.moving)}${guaCard('互卦 · 内在过程',p.mutual)}${guaCard('变卦 · 发展方向',p.changed)}</div><section class="reading-section"><h3>三卦推演</h3><p><b>本卦｜${p.original.name}</b>${hexThemes[p.original.name]}。上卦${p.original.upper.name}象${p.original.upper.image}，下卦${p.original.lower.name}象${p.original.lower.image}；两者说明当前局面既有外部呈现，也有内部基础。</p><p><b>互卦｜${p.mutual.name}</b>${hexThemes[p.mutual.name]}。互卦由本卦二至五爻重组，更适合观察事情在看不见处如何运转，而不是当作另一个结果。</p><p><b>变卦｜${p.changed.name}</b>第${p.moving}爻变化后，趋势转向“${hexThemes[p.changed.name]}”。这是在当前条件延续时较可能出现的方向，不是固定结局。</p></section><section class="reading-section"><h3>体用与建议</h3><p>动爻位于${p.moving<=3?'下卦':'上卦'}，因此以${p.bodyUse.body.name}${p.bodyUse.body.nature}为体、${p.bodyUse.use.name}${p.bodyUse.use.nature}为用，五行关系为<b>${p.bodyUse.relation}</b>：${p.bodyUse.meaning}。</p><p><b>行动建议</b>${hexThemes[p.changed.name]}。把这句话落实到当前问题：${topicGuidance[state.category].action}，完成后再根据新事实判断下一步。</p></section>`}
function psychInterpretation(){const stats=tarotStats(),plum=calculatePlum(),highFriction=stats.reversed>state.drawn.length/2||["困","蹇","坎","否","剥"].includes(plum.original.name);return `<section class="reading-section"><h3>先把象征放回现实</h3><p>塔罗在描述你的心理与行动模式，梅花易数在描述序号和时间形成的变化结构；两者可以互相启发，但都不能替你确认他人的真实想法，也不能把可能性变成必然。</p></section><section class="reading-section"><h3>给此刻的你</h3><p>${highFriction?'两套结果都提示阻力较高。现在最有帮助的不是逼自己立刻得出答案，而是先降低局面的复杂度。':'结果中仍有可以调动的空间。比起等待“更确定”的感觉，一个低风险、可撤回的小行动更能带来真实信息。'}</p><div class="practice"><strong>15分钟现实练习</strong><ol><li>写下一个已经确认的事实，不加入猜测。</li><li>写下一个你最担心的解释，并标注它目前有什么证据。</li><li>执行：${topicGuidance[state.category].action}。</li></ol></div><p>如果问题涉及医疗、法律、投资或人身安全，请优先咨询相应专业人士。象征解读只适合辅助自我觉察。</p></section>`}
function renderCodexAnalysis(analysis){if(!analysis||!Array.isArray(analysis.cardReadings))throw new Error("Codex 返回的解析结构不完整");state.codexAnalysis=analysis;const safe=value=>escapeHtml(String(value||"")),clean=(value,label)=>String(value||"").replace(new RegExp(`^${label}[：:\\s]*`),"");const cardBlocks=analysis.cardReadings.map((item,index)=>`<div class="card-reading"><div class="reading-title"><span>${String(index+1).padStart(2,'0')}</span><strong>${safe(item.title)}</strong></div><p><b>关键词</b>${safe(item.keywords)}</p><p><b>对应问题</b>${safe(item.relevance)}</p><p><b>行动含义</b>${safe(item.advice)}</p></div>`).join("");const actions=(analysis.actions||[]).map((item,index)=>`<li><span>${["今天","下一步","验证","复盘"][index]||`步骤 ${index+1}`}</span><p>${safe(item)}</p></li>`).join("");$("#tarotReading").innerHTML=`<section class="reading-section verdict"><span class="section-kicker">Codex 整体判断</span><h3>${safe(analysis.verdict)}</h3></section><section class="reading-section"><h3>逐牌对应你的问题</h3>${cardBlocks}</section><section class="reading-section"><h3>牌间关系</h3><p>${safe(analysis.relationships)}</p></section><section class="reading-section narrative"><h3>综合解读</h3><p>${safe(analysis.synthesis)}</p></section><section class="reading-section"><h3>可以立刻执行</h3><ol class="action-plan">${actions}</ol></section><section class="reading-section closing"><h3>能量总结：${safe(analysis.energy)}</h3><p>${safe(analysis.closingQuestion)}</p></section>`;const plum=analysis.plum||{};$("#plumReading").innerHTML=`<section class="reading-section"><h3>独立起卦依据</h3><p>${safe(plum.basis)}</p><div class="method-note">本部分只使用抽牌序号与时间，不读取塔罗牌名、牌义或正逆位</div></section><section class="reading-section"><h3>本卦 · 互卦 · 变卦</h3><p><b>本卦</b>${safe(clean(plum.original,"本卦"))}</p><p><b>互卦</b>${safe(clean(plum.mutual,"互卦"))}</p><p><b>变卦</b>${safe(clean(plum.changed,"变卦"))}</p><p><b>推演</b>${safe(clean(plum.interpretation,"推演"))}</p></section>`;$("#psychReading").innerHTML=`<section class="reading-section"><h3>给此刻的你</h3><p>${safe(analysis.support)}</p></section><section class="reading-section"><h3>边界提醒</h3><p>${safe(analysis.disclaimer)}</p><p>牌显示的是当下能量，你的选择随时可以改变走向。</p></section>`}
async function requestCodexReading(){const endpoint=window.TAROT_READING_ENDPOINT||"/api/card-reading";const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:state.question,category:state.category,spread:state.spread,cards:state.drawn.map((d,index)=>({name:d.card.name,englishName:d.card.en,reversed:d.reversed,position:state.spread.positions[index],sequence:state.sequences[index]||index+1})),drawTime:state.drawTime.toISOString()})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`解析服务返回 ${response.status}`);return result}
$("#interpretButton").addEventListener("click",async e=>{const button=e.currentTarget,original=button.textContent;button.disabled=true;button.textContent="Codex 正在解析…";try{renderCodexAnalysis(await requestCodexReading());$("#interpretation").hidden=false;$("#readingActions").hidden=true;saveReading(true);setTimeout(()=>$("#interpretation").scrollIntoView({behavior:"smooth",block:"start"}),100)}catch(error){toast(`解析失败：${error.message}`)}finally{button.disabled=false;button.textContent=original}});
$("#reinterpretButton").addEventListener("click",async e=>{const button=e.currentTarget,original=button.textContent;button.disabled=true;button.textContent="正在生成纯牌义解析…";try{renderCodexAnalysis(await requestCodexReading());saveReading(true);toast("已按纯牌义重新解析");setTimeout(()=>$("#interpretation").scrollIntoView({behavior:"smooth",block:"start"}),100)}catch(error){toast(`重新解析失败：${error.message}`)}finally{button.disabled=false;button.textContent=original}});
$("#saveOnlyButton").addEventListener("click",()=>{saveReading(false);$("#readingActions").hidden=true;toast("抽牌结果已保存到左侧记录")});
function sharePayload(){return{question:state.question,category:state.category,spread:state.spread,selected:state.selected,sequences:state.sequences,drawn:state.drawn.map(d=>({id:d.card.id,reversed:d.reversed})),time:state.drawTime.toISOString(),interpreted:Boolean(state.codexAnalysis),analysis:state.codexAnalysis}}
$("#shareReadingButton").addEventListener("click",async e=>{if(!state.drawn.length){toast("当前没有可以分享的牌面");return}if(!confirm("分享链接将包含你的问题、牌面和解析。获得链接的人都可以查看，链接 7 天后失效。确定生成吗？"))return;const button=e.currentTarget,original=button.textContent;button.disabled=true;button.textContent="正在生成分享链接…";try{const response=await fetch("/api/shares",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reading:sharePayload()})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`分享服务返回 ${response.status}`);$("#shareUrl").value=result.url;$("#sharePanel").hidden=false;toast("公网分享链接已生成");setTimeout(()=>$("#sharePanel").scrollIntoView({behavior:"smooth",block:"nearest"}),80)}catch(error){toast(`生成失败：${error.message}`)}finally{button.disabled=false;button.textContent=original}});
$("#copyShareUrl").addEventListener("click",async()=>{const input=$("#shareUrl");if(!input.value)return;try{await navigator.clipboard.writeText(input.value)}catch{input.select();document.execCommand("copy");input.setSelectionRange(0,0)}toast("链接已复制，任何网络均可打开")});
async function loadSharedReading(){const shareId=new URLSearchParams(location.search).get("share");if(!shareId)return;try{const response=await fetch(`/api/shares/${encodeURIComponent(shareId)}`);const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`分享服务返回 ${response.status}`);const item=result.reading||{},sharedDrawn=Array.isArray(item.drawn)?item.drawn:[];if(!sharedDrawn.length||sharedDrawn.length>10)throw new Error("分享牌面无效");const restored=sharedDrawn.map(entry=>{const id=Number(entry.id);if(!Number.isInteger(id)||id<0||id>=cards.length)throw new Error("分享中包含无法识别的牌");return{card:cards[id],reversed:Boolean(entry.reversed)}});const positions=Array.isArray(item.spread?.positions)?item.spread.positions.slice(0,restored.length).map((position,index)=>String(position||`第 ${index+1} 张`).slice(0,40)):[];while(positions.length<restored.length)positions.push(`第 ${positions.length+1} 张`);state.readingId=null;state.question=String(item.question||"朋友分享的牌面").slice(0,500);state.category=spreads[item.category]?item.category:"general";state.agent="codex";state.spread={name:String(item.spread?.name||"分享牌阵").slice(0,40),description:String(item.spread?.description||"来自朋友的抽牌结果").slice(0,120),positions};state.selected=Array.isArray(item.selected)?item.selected.slice(0,10):restored.map(d=>d.card.id);state.sequences=Array.isArray(item.sequences)?item.sequences.slice(0,10):restored.map((_,index)=>index+1);state.drawn=restored;state.drawTime=new Date(item.time);if(Number.isNaN(state.drawTime.getTime()))state.drawTime=new Date();state.codexAnalysis=item.analysis&&typeof item.analysis==="object"?item.analysis:null;renderResult();$("#resultTitle").textContent="朋友分享的牌面";$("#shareReadingButton").hidden=true;showScreen("result");if(item.interpreted&&state.codexAnalysis){renderCodexAnalysis(state.codexAnalysis);$("#interpretation").hidden=false;$("#readingActions").hidden=true}else{$("#readingActions").hidden=true}toast("已打开朋友分享的抽牌结果")}catch(error){toast(error.message||"分享不存在或已经过期");history.replaceState(null,"",location.pathname)}}
function getHistory(){try{return JSON.parse(localStorage.getItem("mystic-readings")||"[]")}catch{return[]}}
function saveReading(interpreted){const history=getHistory();const item={id:state.readingId||Date.now(),question:state.question,category:state.category,agent:state.agent,spread:state.spread,selected:state.selected,sequences:state.sequences,drawn:state.drawn.map(d=>({id:d.card.id,reversed:d.reversed})),time:state.drawTime.toISOString(),interpreted,analysis:interpreted?state.codexAnalysis:null};state.readingId=item.id;const idx=history.findIndex(x=>x.id===item.id);if(idx>=0){item.pinned=history[idx].pinned;history[idx]=item}else history.unshift(item);localStorage.setItem("mystic-readings",JSON.stringify(history.slice(0,40)));renderHistory()}
function renderHistory(){const list=$("#historyList"),history=getHistory().sort((a,b)=>Number(Boolean(b.pinned))-Number(Boolean(a.pinned))||new Date(b.time)-new Date(a.time));if(!history.length){list.innerHTML='<div class="history-empty">这里会收藏你的每一次<br>问询与牌面</div>';return}list.innerHTML=history.map(x=>`<button class="history-item ${x.id===state.readingId?'active':''} ${x.pinned?'is-pinned':''}" data-id="${x.id}"><strong>${x.pinned?'<i class="pin-mark" aria-label="已置顶">◆</i>':''}${escapeHtml(x.question)}</strong><span>${new Date(x.time).toLocaleDateString('zh-CN')} · ${x.spread.name} · Codex</span></button>`).join('')}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
$("#historyList").addEventListener("click",async e=>{const b=e.target.closest('.history-item');if(!b)return;const item=getHistory().find(x=>x.id===+b.dataset.id);if(!item)return;state.readingId=item.id;state.question=item.question;state.category=item.category;state.agent='codex';state.spread=item.spread;state.selected=item.selected;state.sequences=item.sequences||item.selected.map(id=>id+1);state.drawTime=new Date(item.time);state.drawn=item.drawn.map(d=>({card:cards[d.id],reversed:d.reversed}));state.codexAnalysis=item.analysis||null;renderResult();showScreen('result');if(item.interpreted){$("#readingActions").hidden=true;if(item.analysis){renderCodexAnalysis(item.analysis);$("#interpretation").hidden=false}else{toast("正在用 Codex 更新这条旧解析");try{renderCodexAnalysis(await requestCodexReading());$("#interpretation").hidden=false;saveReading(true)}catch(error){$("#readingActions").hidden=false;toast("旧解析更新失败，可点击开始解析重试")}}}renderHistory();closeSidebar()});
const historyContextMenu=$("#historyContextMenu");let contextHistoryId=null;
function closeHistoryMenu(){historyContextMenu.hidden=true;contextHistoryId=null}
$("#historyList").addEventListener("contextmenu",e=>{const itemButton=e.target.closest('.history-item');if(!itemButton)return;e.preventDefault();const item=getHistory().find(x=>x.id===+itemButton.dataset.id);if(!item)return;contextHistoryId=item.id;$("#pinMenuLabel").textContent=item.pinned?'取消置顶':'置顶记录';historyContextMenu.hidden=false;const menuWidth=156,menuHeight=88;historyContextMenu.style.left=`${Math.min(e.clientX,window.innerWidth-menuWidth-10)}px`;historyContextMenu.style.top=`${Math.min(e.clientY,window.innerHeight-menuHeight-10)}px`});
historyContextMenu.addEventListener("click",e=>{const action=e.target.closest('button')?.dataset.action;if(!action||contextHistoryId===null)return;const history=getHistory(),index=history.findIndex(x=>x.id===contextHistoryId);if(index<0){closeHistoryMenu();return}if(action==='pin'){history[index].pinned=!history[index].pinned;localStorage.setItem("mystic-readings",JSON.stringify(history));toast(history[index].pinned?'已置顶这条问询':'已取消置顶');renderHistory();closeHistoryMenu();return}if(action==='delete'){const question=history[index].question;if(confirm(`确定删除“${question}”吗？此操作无法撤销。`)){history.splice(index,1);localStorage.setItem("mystic-readings",JSON.stringify(history));if(state.readingId===contextHistoryId)reset();renderHistory();toast('问询记录已删除')}closeHistoryMenu()}});
document.addEventListener("click",e=>{if(!e.target.closest('#historyContextMenu'))closeHistoryMenu()});document.addEventListener("keydown",e=>{if(e.key==='Escape')closeHistoryMenu()});window.addEventListener("resize",closeHistoryMenu);
$("#clearHistory").addEventListener("click",()=>{if(confirm("确定清空所有问询记录吗？")){localStorage.removeItem("mystic-readings");state.readingId=null;renderHistory()}});
$("#newReading").addEventListener("click",()=>{$("#shareReadingButton").hidden=false;reset()});$("#menuButton").addEventListener("click",()=>$("#sidebar").classList.add('open'));$("#closeSidebar").addEventListener("click",closeSidebar);function closeSidebar(){$("#sidebar").classList.remove('open')}
$("#soundButton").addEventListener("click",e=>{e.currentTarget.classList.toggle('is-on');toast(e.currentTarget.classList.contains('is-on')?'氛围音已开启（演示）':'氛围音已关闭')});
buildShuffle();renderHistory();loadSharedReading();
